version: "3.3"

services:

  ferret:
    image: wasdev/ferret:1.1
    networks:
      - cirrus-net
    deploy:
      replicas: 2
      labels:
        - "traefik.port=9080"
        - "traefik.docker.network=cirrus-net"
        - "traefik.backend.loadbalancer.sticky=true"


networks:
  cirrus-net:
    driver: overlay
